version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: eshop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d eshop"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db_vol:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  django:
    image: eshop
    build: .
    ports:
      - 8081:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - media_vol:/app/media

volumes:
  db_vol:
  media_vol: