services:
  api:
    image: api
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db
  
  front:
    image: front
    build: ./frontend
    ports:
      - "888:8954"
    depends_on:
      - api

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    healthcheck:
      test: ["CMD", "mysql", "-u root", "-p password", "-e", "USE time_db; SELECT COUNT(*) FROM information_schema.tables;"]
      interval: 15s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
